config/routes.rb
Rails.application.routes.draw do
 
  namespace :page do
    get 'standby/index'
  end
  namespace :users_backoffice do
    get 'calls/index'
    resources :calls
  end
  namespace :users_backoffice do
    get 'tickets/index'
    resources :tickets
  end
  namespace :page do
    get 'moneys/index'
  end
  namespace :users_backoffice do
    get 'moneys/index'
    resources :moneys
  end
  namespace :page do
    get 'scrs/index'
  end
  namespace :users_backoffice do
    get 'scrs/index'
    resources :scrs
  end
  namespace :page do
    get 'obs/index'
  end
  namespace :users_backoffice do
    get 'matchings/index'
    resources :matchings
  end
  namespace :page do
    get 'conts/new'
    get 'plubs/index'
    get 'whoamis/index'
    get 'prods/index'
    get 'welcome/index'
    get 'contacts/index'
    get 'contacts/new'
    get 'infos/index'
    get 'conts/index'
    get 'complaints/index'
    get 'complaints/new'
    get 'demos/index'
    get 'prsas/index'
    get 'fees/index'
    get 'risks/index'
  end
 
    
  mount Ckeditor::Engine => '/ckeditor'
  

  
  namespace :site do
    get 'welcome/index'
    get 'info/index'
  end

 
  namespace :users_backoffice do
    get 'welcome/index'
    resources :users
    get 'abouts/index'
    resources :abouts
    get 'products/index'
    resources :products
    get 'whos/index'
    resources :whos
    get 'publications/index'
    resources :publications
    get 'contacts/index'
    resources :contacts
    get 'banners/index'
    resources :banners
    get 'posts/index'
    resources :posts
    get 'imgs/index'
    resources :imgs
    get 'imagems/index'
    resources :imagems
    get 'credits/index'
    resources :credits
    get 'taxs/index'
    resources :taxs
    get 'outs/index'
    resources :outs
    get 'contents/index'
    resources :contents
    get 'informations/index'
    resources :informations
    resources :infos
    get 'complaints/index'
    resources :complaints
    get 'demos/index'
    resources :demos
    get 'prsas/index'
    resources :prsas
    get 'fees/index'
    resources :fees
    get 'risks/index'
    resources :risks
    get 'correspondent/index'
    resources :correspondents
  end
  
  namespace :admins_backoffice do
    get 'welcome/index' # DASHBOARD
    #get 'admins/index'
    #get 'admins/edit/:id', to: 'admins#edit'
    resources :admins
    # resource :admins, except: [:delete] - a que nao desejo ter   
  end
 
 
  #get 'welcome/index'
  devise_for :users
  devise_for :admins
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
 
  get 'inicio', to: 'site/welcome#index'

  #get 'financeira', to: 'page/welcome/index'

  root to: 'site/welcome#index'
  #root to: 'page/standby#index'



end

app/controllers/users_backoffice/abouts_controller.rb
class UsersBackoffice::AboutsController < UsersBackofficeController
 before_action :set_about, only: [:show, :edit, :update, :destroy]
 before_action :authenticate_user!
  
    # GET /abouts
    # GET /abouts.json
    def index
      @abouts = About.all
    end
  
    # GET /abouts/1
    # GET /abouts/1.json
    def show
    end
  
    # GET /abouts/new
    def new
      @about = About.new
    end
  
    # GET /abouts/1/edit
    def edit
    end
  
    # POST /abouts
    # POST /abouts.json
    def create
      @about = About.new(about_params)
        if @about.save
          redirect_to users_backoffice_abouts_index_path, notice: "Conteudo Criado com Sucesso !"
        else
          render :new
        end
    end
  
    # PATCH/PUT /abouts/1
    # PATCH/PUT /abouts/1.json
    def update
        if @about.update(about_params)
            redirect_to users_backoffice_abouts_index_path, notice: "Conteudo Criado com Sucesso !"
          else
            render :edit
          end
    end
  
    # DELETE /abouts/1
    # DELETE /abouts/1.json
    def destroy
      if @about.destroy
        redirect_to users_backoffice_abouts_path, notice: "Conteudo excluido com Sucesso !"
      else
        render :index
      end
    
    end
  
    private
      # Use callbacks to share common setup or constraints between actions.
      def set_about
        @about = About.find(params[:id])
      end
  
      # Never trust parameters from the scary internet, only allow the white list through.
      def about_params
        params.require(:about).permit(:description, :text, :status)
  
      end
 
    end

app/controllers/users_backoffice/banners_controller.rb
class UsersBackoffice::BannersController < UsersBackofficeController
 
  before_action :set_banner, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  def index
    @banners = Banner.all.page(params[:page]).per(5)
  end

  def show

  end

  def edit
  end

  def new
   @banner = Banner.new
  end

  def create
    @banner = Banner.new(params_banners)
    if @banner.save()
      redirect_to users_backoffice_banners_path, notice: "Banner Criado com Sucesso !"
      else
      render :new
     end
   
  end

  def destroy

    if @banner.destroy
      redirect_to users_backoffice_banners_path, notice: "Banner excluido com Sucesso !"
      else
      render :index
     end
     
  end


  def update

    if @banner.update(params_banners)
    redirect_to users_backoffice_banners_path, notice: "Banner Atualizado com Sucesso !"
    else
    render :edit
   end
 end

 private

 def set_banner
  @banner = Banner.find(params[:id])
 end

  def params_banners
    params.require(:banner).permit(:title,:content,:image,:position,:avatar)
  end

end

app/controllers/users_backoffice/calls_controller.rb
class UsersBackoffice::CallsController < UsersBackofficeController
  before_action :set_call, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  
  # GET /matchings
  # GET /matchings.json
  def index
     @calls = Call.all
  end
    
  # GET /matchings/1
  # GET /matchings/1.json
  def show
  end
 
  # GET /matchings/new
  def new
     @call = Call.new   
  end
  
   # GET /matchings/1/edit
   def edit
   end
   
   # POST /matchings
   # POST /matchings.json
   def create
     @call = Call.new(call_params)
     if @call.save
       redirect_to users_backoffice_calls_path, notice: "Educação Financeira Cadastrado com Sucesso !"
     else
       render 'new'
     end
   end
   
    # PATCH/PUT /matchings/1
    # PATCH/PUT /matchings/1.json
   def update
      if @call.update(call_params)
          redirect_to users_backoffice_calls_path, notice: "Educação Financeira  Atualizado com Sucesso !"
        else
          render :edit
        end
    end
   
     # DELETE /matchings/1
     # DELETE /matchings/1.json
     def destroy
      if @call.destroy
        redirect_to users_backoffice_calls_path, notice: "Educação Financeira  excluido com Sucesso !"
      else
        render :index
      end
    
    end 
   
    private
    # Use callbacks to share common setup or constraints between actions.
    def call_ticket
      @call = Call.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def call_params
      params.require(:call).permit(:title,:description)
    end

end

app/controllers/users_backoffice/complaints_controller.rb
class UsersBackoffice::ComplaintsController < UsersBackofficeController
    before_action :set_complaint, only: [:show, :edit, :update, :destroy]

  # GET /contacts
  # GET /contacts.json
  def index
    @complaints = Complaint.all  
  end

  # GET /contacts/1
  # GET /contacts/1.json
  def show
  end

  # GET /contacts/new
  def new
    @complaint = Complaint.new
  end

  # GET /contacts/1/edit
  def edit
  end

  # POST /contacts
  # POST /contacts.json
  def create
    @complaint = Complaint.new(complaint_params)
      if @complaint.save
      redirect_to page_complaints_index_path, notice: 'Denúncia enviada com Sucesso. Aguarde que Retornaremos o mais rapido possivel ! ' 
      else
      render :index 
      end
  end

  # PATCH/PUT /contacts/1
  # PATCH/PUT /contacts/1.json
  def update
    respond_to do |format|
      if @complaint.update(complaint_params)
        format.html { redirect_to users_backoffice_complaints_path, notice: 'Contact was successfully updated.' }
        format.json { render :show, status: :ok, location: @complaint }
      else
        format.html { render :edit }
        format.json { render json: @complaint.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contacts/1
  # DELETE /contacts/1.json
  def destroy
    if @complaint.destroy
    redirect_to users_backoffice_complaints_path, notice: 'Contact was successfully destroyed.' 
    else
    render :index
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_complaint
      @complaint = Complaint.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def complaint_params
      params.require(:complaint).permit(:description_name, :rg, :cpf, :email, :phone, :address, :title, :content)
    end
end

app/controllers/users_backoffice/contacts_controller.rb
class UsersBackoffice::ContactsController < UsersBackofficeController
  before_action :set_contact, only: [:show, :edit, :update, :destroy]

  # GET /contacts
  # GET /contacts.json
  def index
    @contacts = Contact.all.page(params[:page]).per(5)
  end

  # GET /contacts/1
  # GET /contacts/1.json
  def show
  end

  # GET /contacts/new
  def new
    @contact = Contact.new
  end

  # GET /contacts/1/edit
  def edit
  end

  # POST /contacts
  # POST /contacts.json
  def create
    @contact = Contact.new(contact_params)
      if @contact.save
        redirect_to page_conts_index_path, notice: 'Contato enviado com Sucesso. Aguarde que Retornaremos o mais rapido possivel ! ' 
      else
      render :index 
      end
  end

  # PATCH/PUT /contacts/1
  # PATCH/PUT /contacts/1.json
  def update
    respond_to do |format|
      if @contact.update(contact_params)
        format.html { redirect_to users_backoffice_contacts_path, notice: 'Contact was successfully updated.' }
        format.json { render :show, status: :ok, location: @contact }
      else
        format.html { render :edit }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contacts/1
  # DELETE /contacts/1.json
  def destroy
    if @contact.destroy
    redirect_to users_backoffice_contacts_path, notice: 'Contact was successfully destroyed.' 
    else
    render :index
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_contact
      @contact = Contact.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def contact_params
      params.require(:contact).permit(:description_name, :rg, :cpf, :email, :phone, :address, :title, :content)
    end
end

app/controllers/users_backoffice/contents_controller.rb
class UsersBackoffice::ContentsController < UsersBackofficeController
    before_action :set_content, only: [:show, :edit, :update, :destroy]
    before_action :authenticate_user!
  
    # GET /abouts
    # GET /abouts.json
    def index
      @contents = Content.all
    end
  
    # GET /abouts/1
    # GET /abouts/1.json
    def show
    end
  
    # GET /abouts/new
    def new
      @content = Content.new
    end
  
    # GET /abouts/1/edit
    def edit
    end
  
    # POST /abouts
    # POST /abouts.json
    def create
      @content = Content.new(content_params)
        if @content.save
          redirect_to users_backoffice_contents_index_path, notice: "Conteudo Criado com Sucesso !"
        else
          render :new
        end
    end
  
    # PATCH/PUT /abouts/1
    # PATCH/PUT /abouts/1.json
    def update
        if @content.update(content_params)
            redirect_to users_backoffice_contents_index_path, notice: "Conteudo Criado com Sucesso !"
          else
            render :edit
          end
    end
  
    # DELETE /abouts/1
    # DELETE /abouts/1.json
    def destroy
      if @content.destroy
        redirect_to users_backoffice_contents_path, notice: "Conteudo excluido com Sucesso !"
      else
        render :index
      end
    
    end
  
    private
      # Use callbacks to share common setup or constraints between actions.
      def set_content
        @content = Content.find(params[:id])
      end
  
      # Never trust parameters from the scary internet, only allow the white list through.
      def content_params
        params.require(:content).permit(:title, :address, :phone, :email, :phone_two) 
      end
 

end

app/controllers/users_backoffice/correspondents_controller.rb
class UsersBackoffice::CorrespondentsController < UsersBackofficeController
  before_action :set_correspondent, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
   
     # GET /abouts
     # GET /abouts.json
     def index
       @correspondents = Correspondent.all
     end
   
     # GET /abouts/1
     # GET /abouts/1.json
     def show
     end
   
     # GET /abouts/new
     def new
       @correspondent = Correspondent.new
     end
   
     # GET /abouts/1/edit
     def edit
     end
   
     # POST /abouts
     # POST /abouts.json
     def create
       @correspondent = Correspondent.new(correspondent_params)
         if @correspondent.save
           redirect_to users_backoffice_correspondents_path, notice: "Correspodente Criado com Sucesso !"
         else
           render :new
         end
     end
   
     # PATCH/PUT /abouts/1
     # PATCH/PUT /abouts/1.json
     def update
         if @correspondent.update(correspondent_params)
             redirect_to users_backoffice_correspondents_path, notice: "Correspodente Atualizado com Sucesso !"
           else
             render :edit
           end
     end
   
     # DELETE /abouts/1
     # DELETE /abouts/1.json
     def destroy
       if @correspondent.destroy
         redirect_to users_backoffice_correspondents_path, notice: "TCorrespodente excluido com Sucesso !"
       else
         render :index
       end
     
     end
   
     private
       # Use callbacks to share common setup or constraints between actions.
       def set_risk
         @correspondent = Correspondent.find(params[:id])
       end
   
       # Never trust parameters from the scary internet, only allow the white list through.
       def correspondent_params
         params.require(:correspondent).permit(:name, :description )
   
       end
end

app/controllers/users_backoffice/credits_controller.rb
class UsersBackoffice::CreditsController < UsersBackofficeController
  before_action :set_credit, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  
    # GET /posts
    # GET /posts.json
    def index
      @credits = Credit.all
    end
  
    # GET /posts/1
    # GET /posts/1.json
    def show
    end
  
    # GET /posts/new
    def new
      @credit = Credit.new
    end
  
    # GET /abouts/1/edit
    def edit
    end
  
    # POST /abouts
    # POST /abouts.json
    def create
      @credit = Credit.new(credit_params)
        if @credit.save
          redirect_to users_backoffice_credits_index_path, notice: "Posts Criado com Sucesso !"
        else
          render :new
        end
    end
  
    # PATCH/PUT /abouts/1
    # PATCH/PUT /abouts/1.json
    def update
        if @credit.update(credit_params)
            redirect_to users_backoffice_credits_index_path, notice: "Posts Criado com Sucesso !"
          else
            render :edit
          end
    end
  
    # DELETE /abouts/1
    # DELETE /abouts/1.json
    def destroy
      if @credit.destroy
        redirect_to users_backoffice_credits_path, notice: "Posts excluido com Sucesso !"
      else
        render :index
      end
    
    end
  
    private
      # Use callbacks to share common setup or constraints between actions.
      def set_credit
        @credit = Credit.find(params[:id])
      end
  
      # Never trust parameters from the scary internet, only allow the white list through.
      def credit_params
        params.require(:credit).permit(:title, :content, :status)
      end
end

app/controllers/users_backoffice/fees_controller.rb
class UsersBackoffice::FeesController < UsersBackofficeController
 before_action :set_fee, only: [:show, :edit, :update, :destroy]
 before_action :authenticate_user!
  
    # GET /abouts
    # GET /abouts.json
    def index
      @fees = Fee.all
    end
  
    # GET /abouts/1
    # GET /abouts/1.json
    def show
    end
  
    # GET /abouts/new
    def new
      @fee = Fee.new
    end
  
    # GET /abouts/1/edit
    def edit
    end
  
    # POST /abouts
    # POST /abouts.json
    def create
        @fee = Fee.new(fees_params)
        if @fee.save
          redirect_to users_backoffice_fees_index_path, notice: "FEES Criado com Sucesso !"
        else
          render :new
        end
    end
  
    # PATCH/PUT /abouts/1
    # PATCH/PUT /abouts/1.json
    def update
        if @fees.update(fees_params)
            redirect_to users_backoffice_fees_index_path, notice: "FEES Atualizado com Sucesso !"
          else
            render :edit
          end
    end
  
    # DELETE /abouts/1
    # DELETE /abouts/1.json
    def destroy
      if @fee.destroy
        redirect_to users_backoffice_fees_path, notice: "FEES excluido com Sucesso !"
      else
        render :index
      end
    
    end
  
    private
      # Use callbacks to share common setup or constraints between actions.
      def set_fee
        @fee = Fee.find(params[:id])
      end
  
      # Never trust parameters from the scary internet, only allow the white list through.
      def fees_params
        params.require(:fee).permit(:title, :content )
  
      end
end

app/views/users_backoffice/publications/_form.html.erb
<%#= form_with(model: publication, local: true) do |form| %>
<%= form_with(model: [ :users_backoffice, @publication], local: true) do |form| %>
  <% if publication.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(publication.errors.count, "error") %> prohibited this publication from being saved:</h2>

      <ul>
      <% publication.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :content %>
    <%= form.cktext_area :content %>
  </div>

  <div class="input-field">
   <input type="checkbox" checked="checked" />  <%= form.check_box :status %> 
   <span> <%= form.label :status %> </span>
  </div>

<br/>

    <div class="file-field input-field">
      <div class="btn">
        <span> Arquivos PDF </span>
        <%= form.file_field :documents, multiple: true %> 
      </div>
      <div class="file-path-wrapper">
        <input class="file-path validate" type="text" placeholder="Um ou mais arquivos">
      </div>
    </div>
  
<br>
  <div class="actions">
  <a class="waves-effect grey btn">  <%= form.submit %> </a> 
  </div>
<% end %>

app/views/users_backoffice/publications/edit.html.erb
<div class="container">
<h1> Editar Publicação </h1>

<%= render 'form', publication: @publication %>
<br>
<%= link_to 'Mostar', users_backoffice_publication_path(@publication) , class: "waves-effect green btn"%> |
<%= link_to 'Voltar', users_backoffice_publications_path , class: "waves-effect yellow btn"%>
</div>

app/views/users_backoffice/publications/index.html.erb
<div class="container">
<p id="notice"><%= notice %></p>

<h1> Listagem de Publicações </h1>


<table class="bordered highlight right">
  <thead>
    <tr> </tr>
    <tr>
      <th> <%= link_to 'New Publication', new_users_backoffice_publication_path, class: "waves-effect blue btn" %> </th>
    </tr>
  </thead>


<table class="bordered highlight centered">
  <thead>
    <tr>
      <th> Titulo </th>
      <th> Conteudo </th>
      <th> Status </th>
      <th> File - Arquivos </th>
      <th> Ações <th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @publications.each do |publication| %>
      <tr>
        <td><%= publication.title %></td>
        <td><%= publication.content.html_safe %></td>
        <td><%= publication.status %> </td>
       
        <td><%= link_to 'Mostrar', users_backoffice_publication_path(publication) ,  class: "waves-effect green btn"%></td>
       
      
        <td><%= link_to 'Editar', edit_users_backoffice_publication_path(publication),  class: "waves-effect yellow btn" %></td>
      
     
        <td><%= link_to 'Excluir', users_backoffice_publication_path(publication) , method: :delete, data: { confirm: 'Are you sure?' } , class: "waves-effect red btn"%></td>
      
      </tr>
    <% end %>
  </tbody>
</table>

<br>


</div>

app/views/users_backoffice/publications/new.html.erb
<div class="container">
<h1> Nova Publicação </h1>

<%= render 'form', publication: @publication %>

<%= link_to 'Voltar', users_backoffice_publications_path  , class: "waves-effect yellow btn"%>
</div>

app/views/users_backoffice/publications/show.html.erb
<div class="container">
<p id="notice"><%= notice %></p>

<h1> Mostra de Publicações </h1>

<table>
        <thead>
          <tr>
              <th> <strong> Titulo:</strong> </th>
              <td> <strong> Conteúdo:</strong></td>
              <td> <strong> Status: </strong></td>
              <td> <strong> Documentos : </strong> </td>
              <th><strong> Ações:  </strong></th>
          </tr>
        </thead>

        <tbody>
          <tr>
            
            <td><%= @publication.title %> </td>
            <td>  <%= @publication.content.html_safe %> </td>
            <td> <%= @publication.status %> </td>
            <td>  <% @publication.documents.each_with_index do |document,index|%> </td>
            <td> <%#= @publication.document %>
            <td> <%#= @publication.document.url %>
             <td> <%= link_to("Anexo #(index+1)", document.url, target: '_blank')%> </td>
            <br/>
            <% end %>
            <%= link_to 'Editar', edit_users_backoffice_publication_path(@publication) , class: "waves-effect green btn" %> |
<%= link_to 'Voltar', users_backoffice_publications_path, class: "waves-effect yellow btn"  %>
            </td>
          </tr>
        </tbody>
      </table>

</div>      